[package]
name = "inference"
version.workspace = true
edition.workspace = true

[dependencies]
vision = { workspace = true }
rand = "0.8"
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = [
    "std",
    "webgpu",
    "tls-rustls",
    "download-binaries",
    "copy-dylibs",
]

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
