[env]
LIBCLANG_PATH = "/usr/lib"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
    "-Lnative=/home/torchi/.xwin-cache/splat/crt/lib/x86_64",
    "-Lnative=/home/torchi/.xwin-cache/splat/sdk/lib/ucrt/x86_64",
    "-Lnative=/home/torchi/.xwin-cache/splat/sdk/lib/um/x86_64",
    "-Ctarget-feature=+crt-static",
]
