[package]
name = "porda-core"
version.workspace = true
edition.workspace = true

[dependencies]
config = { workspace = true }
vision = { workspace = true }
capture = { workspace = true }
inference = { workspace = true }
overlay = { workspace = true }
platform = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
